name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Configure Solver
     run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build

   - name: Built Solver
     run: cmake --build ${{github.workspace}}/solver_application/build

   - name: Configure HelloWorld
     run: cmake ${{github.workspace}}/hello_world_application/ -B ${{github.workspace}}/hello_world_application/build

   - name: Built HelloWorld
     run: cmake --build ${{github.workspace}}/hello_world_application/build
